export { default as Home } from "./home/Home"
export { default as About } from "./about/About"
export { default as Register } from "./auth/Register"
export { default as Login } from "./auth/Login"
export { default as Ads } from "./ads/Ads"
export { default as News } from "./news/News"